version: '3.4'

services:
  cinebox-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Av@ntur@
      - MSSQL_PID=Developer
    ports:
      - 1402:1433
    expose:
      - 1433
    networks:
      - cinebox

  cinebox-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=${DB_SERVER},${DB_PORT};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7137:7137
    networks:
      - cinebox
    links:
      - cinebox-sql
    depends_on:
      - cinebox-sql

  cinebox-rabbitmq:
    image: "rabbitmq:3-management"
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - cinebox

networks:
  cinebox:
    driver: bridge
