// <auto-generated />
using System;
using CineBox.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineBox.Services.Migrations
{
    [DbContext(typeof(CineBoxContext))]
    [Migration("20240723132949_CineBoxInitializerV1")]
    partial class CineBoxInitializerV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineBox.Services.Database.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Actor__3213E83F2E81C85E");

                    b.ToTable("Actor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kate Winslet"
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotion_Id");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int")
                        .HasColumnName("screening_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Booking__3213E83F4DE83FAA");

                    b.HasIndex("PromotionId");

                    b.HasIndex("ScreeningId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 25.00m,
                            PromotionId = 1,
                            ScreeningId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Price = 30.00m,
                            PromotionId = 1,
                            ScreeningId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.BookingSeat", b =>
                {
                    b.Property<int>("BookingSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bookingSeatId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingSeatId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.HasKey("BookingSeatId")
                        .HasName("PK__BookingS__0F3B47D633C275B0");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId");

                    b.ToTable("BookingSeat", (string)null);

                    b.HasData(
                        new
                        {
                            BookingSeatId = 1,
                            BookingId = 1,
                            SeatId = 1
                        },
                        new
                        {
                            BookingSeatId = 2,
                            BookingId = 1,
                            SeatId = 2
                        },
                        new
                        {
                            BookingSeatId = 3,
                            BookingId = 2,
                            SeatId = 3
                        },
                        new
                        {
                            BookingSeatId = 4,
                            BookingId = 2,
                            SeatId = 4
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Cinema__3213E83F23CFAD71");

                    b.ToTable("Cinema", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "New York",
                            Name = "Cineworld"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Los Angeles",
                            Name = "IMAX"
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Genre__3213E83F38AFBD04");

                    b.ToTable("Genre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int")
                        .HasColumnName("cinema_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Hall__3213E83FD9AF1396");

                    b.HasIndex("CinemaId");

                    b.ToTable("Hall", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            Name = "Hall 1"
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 2,
                            Name = "Hall 2"
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("director");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.Property<DateTime>("PerformedFrom")
                        .HasColumnType("date")
                        .HasColumnName("performed_from");

                    b.Property<DateTime>("PerformedTo")
                        .HasColumnType("date")
                        .HasColumnName("performed_to");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("picture");

                    b.Property<byte[]>("PictureThumb")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("pictureThumb");

                    b.Property<string>("StateMachine")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stateMachine");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Movie__3213E83F2BD5909A");

                    b.HasIndex("GenreId");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A mind-bending thriller",
                            Director = "Christopher Nolan",
                            GenreId = 1,
                            PerformedFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformedTo = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A romantic disaster film",
                            Director = "James Cameron",
                            GenreId = 1,
                            PerformedFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformedTo = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.MovieActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int")
                        .HasColumnName("actor_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.HasKey("Id")
                        .HasName("PK__MovieAct__3213E83F842B29CF");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActor", (string)null);
                });

            modelBuilder.Entity("CineBox.Services.Database.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int")
                        .HasColumnName("cinema_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__News__3213E83F8B80E9AE");

                    b.HasIndex("CinemaId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("CineBox.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("payment_status");

                    b.HasKey("Id")
                        .HasName("PK__Payment__3213E83F05BAE6AD");

                    b.HasIndex("BookingId");

                    b.ToTable("Payment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 25.00m,
                            BookingId = 1,
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 30.00m,
                            BookingId = 2,
                            PaymentStatus = "Completed"
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("discount");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3213E83FC04BB357");

                    b.ToTable("Promotion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SUMMER20",
                            Discount = 20.00m,
                            ExpirationDate = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Review__3213E83FD26CF094");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Review", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Amazing movie!",
                            MovieId = 1,
                            Rating = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Very touching film.",
                            MovieId = 2,
                            Rating = 4,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3213E83F76DBADCD");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CineBox.Services.Database.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("hall_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("ScreeningTime")
                        .HasColumnType("datetime")
                        .HasColumnName("screening_time");

                    b.HasKey("Id")
                        .HasName("PK__Screenin__3213E83F341DB2BE");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Screening", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Standard",
                            HallId = 1,
                            MovieId = 1,
                            Price = 12.50m,
                            ScreeningTime = new DateTime(2024, 7, 24, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Premium",
                            HallId = 2,
                            MovieId = 2,
                            Price = 15.00m,
                            ScreeningTime = new DateTime(2024, 7, 24, 22, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("hall_id");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("seat_number");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Seat__3213E83F0DCCBA47");

                    b.HasIndex("HallId");

                    b.ToTable("Seat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Standard",
                            HallId = 1,
                            SeatNumber = 1,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Category = "Standard",
                            HallId = 1,
                            SeatNumber = 2,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Category = "Premium",
                            HallId = 2,
                            SeatNumber = 1,
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Category = "Premium",
                            HallId = 2,
                            SeatNumber = 2,
                            Status = true
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingSeatId")
                        .HasColumnType("int")
                        .HasColumnName("booking_seat_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("qr_code");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket_code");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Ticket__3213E83FBF00AE8F");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "BookingSeatId" }, "UQ__Ticket__C073D47C7F315E70")
                        .IsUnique();

                    b.ToTable("Ticket", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingSeatId = 1,
                            Price = 12.50m,
                            QrCode = "QR001",
                            TicketCode = "TICKET001",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingSeatId = 2,
                            Price = 12.50m,
                            QrCode = "QR002",
                            TicketCode = "TICKET002",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookingSeatId = 3,
                            Price = 15.00m,
                            QrCode = "QR003",
                            TicketCode = "TICKET003",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookingSeatId = 4,
                            Price = 15.00m,
                            QrCode = "QR004",
                            TicketCode = "TICKET004",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordSalt");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F430A5CF0");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            Name = "John",
                            PasswordHash = "hash1",
                            PasswordSalt = "salt1",
                            Phone = "123-456-7890",
                            Status = true,
                            Surname = "Doe",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            Name = "Jane",
                            PasswordHash = "hash2",
                            PasswordSalt = "salt2",
                            Phone = "987-654-3210",
                            Status = true,
                            Surname = "Smith",
                            Username = "jane_smith"
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.UsersRole", b =>
                {
                    b.Property<int>("UsersRolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsersRolesId"));

                    b.Property<DateTime>("DateOfModification")
                        .HasColumnType("datetime")
                        .HasColumnName("dateOfModification");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UsersRolesId")
                        .HasName("PK__UsersRol__A9752347C3F9B8FD");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersRoles");

                    b.HasData(
                        new
                        {
                            UsersRolesId = 1,
                            DateOfModification = new DateTime(2024, 7, 23, 15, 29, 49, 84, DateTimeKind.Local).AddTicks(7140),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            UsersRolesId = 2,
                            DateOfModification = new DateTime(2024, 7, 23, 15, 29, 49, 84, DateTimeKind.Local).AddTicks(7200),
                            RoleId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CineBox.Services.Database.Booking", b =>
                {
                    b.HasOne("CineBox.Services.Database.Promotion", "Promotion")
                        .WithMany("Bookings")
                        .HasForeignKey("PromotionId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Promotion");

                    b.HasOne("CineBox.Services.Database.Screening", "Screening")
                        .WithMany("Bookings")
                        .HasForeignKey("ScreeningId")
                        .IsRequired()
                        .HasConstraintName("FK__Booking__screeni__4D94879B");

                    b.HasOne("CineBox.Services.Database.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Booking__user_id__4CA06362");

                    b.Navigation("Promotion");

                    b.Navigation("Screening");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CineBox.Services.Database.BookingSeat", b =>
                {
                    b.HasOne("CineBox.Services.Database.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingSe__booki__6477ECF3");

                    b.HasOne("CineBox.Services.Database.Seat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK__BookingSe__seat___656C112C");

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("CineBox.Services.Database.Hall", b =>
                {
                    b.HasOne("CineBox.Services.Database.Cinema", "Cinema")
                        .WithMany("Halls")
                        .HasForeignKey("CinemaId")
                        .IsRequired()
                        .HasConstraintName("FK__Hall__cinema_id__45F365D3");

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("CineBox.Services.Database.Movie", b =>
                {
                    b.HasOne("CineBox.Services.Database.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("FK__Movie__genre_id__412EB0B6");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CineBox.Services.Database.MovieActor", b =>
                {
                    b.HasOne("CineBox.Services.Database.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .IsRequired()
                        .HasConstraintName("FK__MovieActo__actor__5CD6CB2B");

                    b.HasOne("CineBox.Services.Database.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__MovieActo__movie__5BE2A6F2");

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CineBox.Services.Database.News", b =>
                {
                    b.HasOne("CineBox.Services.Database.Cinema", "Cinema")
                        .WithMany("News")
                        .HasForeignKey("CinemaId")
                        .IsRequired()
                        .HasConstraintName("FK__News__cinema_id__02FC7413");

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("CineBox.Services.Database.Payment", b =>
                {
                    b.HasOne("CineBox.Services.Database.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__Payment__booking__534D60F1");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CineBox.Services.Database.Review", b =>
                {
                    b.HasOne("CineBox.Services.Database.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__movie_id__571DF1D5");

                    b.HasOne("CineBox.Services.Database.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__user_id__5629CD9C");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CineBox.Services.Database.Screening", b =>
                {
                    b.HasOne("CineBox.Services.Database.Hall", "Hall")
                        .WithMany("Screenings")
                        .HasForeignKey("HallId")
                        .IsRequired()
                        .HasConstraintName("FK__Screening__hall___49C3F6B7");

                    b.HasOne("CineBox.Services.Database.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__Screening__movie__48CFD27E");

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CineBox.Services.Database.Seat", b =>
                {
                    b.HasOne("CineBox.Services.Database.Hall", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("HallId")
                        .IsRequired()
                        .HasConstraintName("FK__Seat__status__5FB337D6");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("CineBox.Services.Database.Ticket", b =>
                {
                    b.HasOne("CineBox.Services.Database.BookingSeat", "BookingSeat")
                        .WithOne("Ticket")
                        .HasForeignKey("CineBox.Services.Database.Ticket", "BookingSeatId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_BookingSeat");

                    b.HasOne("CineBox.Services.Database.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_User");

                    b.Navigation("BookingSeat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CineBox.Services.Database.UsersRole", b =>
                {
                    b.HasOne("CineBox.Services.Database.Role", "Role")
                        .WithMany("UsersRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersRole__role___3E52440B");

                    b.HasOne("CineBox.Services.Database.User", "User")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UsersRole__user___3D5E1FD2");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CineBox.Services.Database.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("CineBox.Services.Database.Booking", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CineBox.Services.Database.BookingSeat", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CineBox.Services.Database.Cinema", b =>
                {
                    b.Navigation("Halls");

                    b.Navigation("News");
                });

            modelBuilder.Entity("CineBox.Services.Database.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CineBox.Services.Database.Hall", b =>
                {
                    b.Navigation("Screenings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CineBox.Services.Database.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("Reviews");

                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("CineBox.Services.Database.Promotion", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CineBox.Services.Database.Role", b =>
                {
                    b.Navigation("UsersRoles");
                });

            modelBuilder.Entity("CineBox.Services.Database.Screening", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CineBox.Services.Database.Seat", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("CineBox.Services.Database.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("Tickets");

                    b.Navigation("UsersRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
